//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoutoNavigator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public tag()
        {
            this.tagset_tag_connection = new HashSet<tagset_tag_connection>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int id_type { get; set; }
    
        public virtual tag_type tag_type { get; set; }
        public virtual ICollection<tagset_tag_connection> tagset_tag_connection { get; set; }
    }
}
