//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoutoNavigator.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TagsDBEntities : DbContext
    {
        public TagsDBEntities()
            : base("name=TagsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<tag_type> tag_type { get; set; }
        public virtual DbSet<tagset> tagsets { get; set; }
        public virtual DbSet<tagset_tag_connection> tagset_tag_connection { get; set; }
    }
}
