//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<<< HEAD:Source/ImoutoRebirth.Navigator/ImoutoRebirth.Navigator/Settings.Designer.cs
namespace ImoutoRebirth.Navigator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
========
using ImoutoViewer.ViewModel;
using ImoutoViewer.ViewModel.SettingsModels;

namespace ImoutoViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
>>>>>>>> ImoutoViewer/master:Source/ImoutoViewer/Properties/Settings.Designer.cs
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<<< HEAD:Source/ImoutoRebirth.Navigator/ImoutoRebirth.Navigator/Settings.Designer.cs
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
========
        [global::System.Configuration.DefaultSettingValueAttribute("DownscaleToViewPort")]
        public ResizeType ResizeType {
            get {
                return ((ResizeType)(this["ResizeType"]));
            }
            set {
                this["ResizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Folder, Subfolders")]
        public global::ImoutoViewer.Model.DirectorySearchFlags DirectorySearchFlags {
            get {
                return ((global::ImoutoViewer.Model.DirectorySearchFlags)(this["DirectorySearchFlags"]));
            }
            set {
                this["DirectorySearchFlags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ByName")]
        public global::ImoutoViewer.Model.SortMethod FilesSorting {
            get {
                return ((global::ImoutoViewer.Model.SortMethod)(this["FilesSorting"]));
            }
            set {
                this["FilesSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ByName")]
        public global::ImoutoViewer.Model.SortMethod FoldersSorting {
            get {
                return ((global::ImoutoViewer.Model.SortMethod)(this["FoldersSorting"]));
            }
            set {
                this["FoldersSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilesSortingDesc {
            get {
                return ((bool)(this["FilesSortingDesc"]));
            }
            set {
                this["FilesSortingDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FoldersSortingDesc {
            get {
                return ((bool)(this["FoldersSortingDesc"]));
            }
            set {
                this["FoldersSortingDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
>>>>>>>> ImoutoViewer/master:Source/ImoutoViewer/Properties/Settings.Designer.cs
        public string AccentColorName {
            get {
                return ((string)(this["AccentColorName"]));
            }
            set {
                this["AccentColorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThemeIndex {
            get {
                return ((int)(this["ThemeIndex"]));
            }
            set {
                this["ThemeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActivatePreviewOnSelect {
            get {
                return ((bool)(this["ActivatePreviewOnSelect"]));
            }
            set {
                this["ActivatePreviewOnSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathOverrides {
            get {
                return ((string)(this["PathOverrides"]));
            }
            set {
                this["PathOverrides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11302/")]
        public string LilinHost {
            get {
                return ((string)(this["LilinHost"]));
            }
            set {
                this["LilinHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11301/")]
        public string RoomHost {
            get {
                return ((string)(this["RoomHost"]));
            }
            set {
                this["RoomHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValue("False")]
        public bool ShowSystemTags {
            get {
                return ((bool)(this["ShowSystemTags"]));
            }
            set {
                this["ShowSystemTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotes {
            get {
                return ((bool)(this["ShowNotes"]));
            }
            set {
                this["ShowNotes"] = value;
            }
        }
    }
}
