// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BindTagsRequest
    {
        /// <summary>
        /// Initializes a new instance of the BindTagsRequest class.
        /// </summary>
        public BindTagsRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BindTagsRequest class.
        /// </summary>
        public BindTagsRequest(IList<FileTagRequest> fileTags)
        {
            FileTags = fileTags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileTags")]
        public IList<FileTagRequest> FileTags { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FileTags == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FileTags");
            }
            if (FileTags != null)
            {
                foreach (var element in FileTags)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
