// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FileTagResponseTag : TagResponse
    {
        /// <summary>
        /// Initializes a new instance of the FileTagResponseTag class.
        /// </summary>
        public FileTagResponseTag()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileTagResponseTag class.
        /// </summary>
        public FileTagResponseTag(System.Guid id, bool hasValue, int count, TagResponseType type = default(TagResponseType), string name = default(string), IList<string> synonyms = default(IList<string>))
            : base(id, hasValue, count, type, name, synonyms)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
