// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using System.Linq;

    public partial class FileNoteResponseNote : NoteResponse
    {
        /// <summary>
        /// Initializes a new instance of the FileNoteResponseNote class.
        /// </summary>
        public FileNoteResponseNote()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileNoteResponseNote class.
        /// </summary>
        public FileNoteResponseNote(System.Guid id, int positionFromLeft, int positionFromTop, int width, int height, string label = default(string))
            : base(id, positionFromLeft, positionFromTop, width, height, label)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
