// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FileTagRequest
    {
        /// <summary>
        /// Initializes a new instance of the FileTagRequest class.
        /// </summary>
        public FileTagRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileTagRequest class.
        /// </summary>
        /// <param name="source">Possible values include: 'Yandere',
        /// 'Danbooru', 'Sankaku', 'Manual'</param>
        public FileTagRequest(System.Guid tagId, System.Guid fileId, MetadataSource source, string value = default(string))
        {
            TagId = tagId;
            FileId = fileId;
            Source = source;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tagId")]
        public System.Guid TagId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileId")]
        public System.Guid FileId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Yandere', 'Danbooru',
        /// 'Sankaku', 'Manual'
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public MetadataSource Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
