// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NoteResponse
    {
        /// <summary>
        /// Initializes a new instance of the NoteResponse class.
        /// </summary>
        public NoteResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NoteResponse class.
        /// </summary>
        public NoteResponse(System.Guid id, int positionFromLeft, int positionFromTop, int width, int height, string label = default(string))
        {
            Id = id;
            Label = label;
            PositionFromLeft = positionFromLeft;
            PositionFromTop = positionFromTop;
            Width = width;
            Height = height;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionFromLeft")]
        public int PositionFromLeft { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionFromTop")]
        public int PositionFromTop { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public int Width { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int Height { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
