// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for RelativeType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RelativeType
    {
        [EnumMember(Value = "Child")]
        Child,
        [EnumMember(Value = "Parent")]
        Parent
    }
    internal static class RelativeTypeEnumExtension
    {
        internal static string ToSerializedValue(this RelativeType? value)
        {
            return value == null ? null : ((RelativeType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this RelativeType value)
        {
            switch( value )
            {
                case RelativeType.Child:
                    return "Child";
                case RelativeType.Parent:
                    return "Parent";
            }
            return null;
        }

        internal static RelativeType? ParseRelativeType(this string value)
        {
            switch( value )
            {
                case "Child":
                    return RelativeType.Child;
                case "Parent":
                    return RelativeType.Parent;
            }
            return null;
        }
    }
}
