// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// FileInfo of file in system to which found relative is related.
    /// </summary>
    public partial class RelativeResponseFileInfo : FileInfoResponse
    {
        /// <summary>
        /// Initializes a new instance of the RelativeResponseFileInfo class.
        /// </summary>
        public RelativeResponseFileInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RelativeResponseFileInfo class.
        /// </summary>
        public RelativeResponseFileInfo(IList<FileTagResponse> tags = default(IList<FileTagResponse>), IList<FileNoteResponse> notes = default(IList<FileNoteResponse>))
            : base(tags, notes)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
