// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RelativeResponse
    {
        /// <summary>
        /// Initializes a new instance of the RelativeResponse class.
        /// </summary>
        public RelativeResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RelativeResponse class.
        /// </summary>
        /// <param name="relativesType">Type of relative with md5 from request.
        /// Possible values include: 'Child', 'Parent'</param>
        /// <param name="fileInfo">FileInfo of file in system to which found
        /// relative is related.</param>
        public RelativeResponse(RelativeType relativesType, RelativeResponseFileInfo fileInfo = default(RelativeResponseFileInfo))
        {
            RelativesType = relativesType;
            FileInfo = fileInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets type of relative with md5 from request. Possible values
        /// include: 'Child', 'Parent'
        /// </summary>
        [JsonProperty(PropertyName = "relativesType")]
        public RelativeType RelativesType { get; private set; }

        /// <summary>
        /// Gets fileInfo of file in system to which found relative is related.
        /// </summary>
        [JsonProperty(PropertyName = "fileInfo")]
        public RelativeResponseFileInfo FileInfo { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
