// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for SameTagHandleStrategy.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SameTagHandleStrategy
    {
        [EnumMember(Value = "ReplaceExistingValue")]
        ReplaceExistingValue,
        [EnumMember(Value = "AddNewFileTag")]
        AddNewFileTag
    }
    internal static class SameTagHandleStrategyEnumExtension
    {
        internal static string ToSerializedValue(this SameTagHandleStrategy? value)
        {
            return value == null ? null : ((SameTagHandleStrategy)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this SameTagHandleStrategy value)
        {
            switch( value )
            {
                case SameTagHandleStrategy.ReplaceExistingValue:
                    return "ReplaceExistingValue";
                case SameTagHandleStrategy.AddNewFileTag:
                    return "AddNewFileTag";
            }
            return null;
        }

        internal static SameTagHandleStrategy? ParseSameTagHandleStrategy(this string value)
        {
            switch( value )
            {
                case "ReplaceExistingValue":
                    return SameTagHandleStrategy.ReplaceExistingValue;
                case "AddNewFileTag":
                    return SameTagHandleStrategy.AddNewFileTag;
            }
            return null;
        }
    }
}
