// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using System.Linq;

    public partial class TagResponseType : TagTypeResponse
    {
        /// <summary>
        /// Initializes a new instance of the TagResponseType class.
        /// </summary>
        public TagResponseType()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TagResponseType class.
        /// </summary>
        public TagResponseType(System.Guid id, int color, string name = default(string))
            : base(id, color, name)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
