// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TagResponse
    {
        /// <summary>
        /// Initializes a new instance of the TagResponse class.
        /// </summary>
        public TagResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TagResponse class.
        /// </summary>
        public TagResponse(System.Guid id, bool hasValue, int count, TagResponseType type = default(TagResponseType), string name = default(string), IList<string> synonyms = default(IList<string>))
        {
            Id = id;
            Type = type;
            Name = name;
            HasValue = hasValue;
            Synonyms = synonyms;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public TagResponseType Type { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasValue")]
        public bool HasValue { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "synonyms")]
        public IList<string> Synonyms { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int Count { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type != null)
            {
                Type.Validate();
            }
        }
    }
}
