// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TagSearchEntryRequest
    {
        /// <summary>
        /// Initializes a new instance of the TagSearchEntryRequest class.
        /// </summary>
        public TagSearchEntryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TagSearchEntryRequest class.
        /// </summary>
        /// <param name="tagSearchScope">Possible values include: 'Included',
        /// 'Excluded'</param>
        public TagSearchEntryRequest(System.Guid tagId, TagSearchScope tagSearchScope, string value = default(string))
        {
            TagId = tagId;
            Value = value;
            TagSearchScope = tagSearchScope;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tagId")]
        public System.Guid TagId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Included', 'Excluded'
        /// </summary>
        [JsonProperty(PropertyName = "tagSearchScope")]
        public TagSearchScope TagSearchScope { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
