// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TagsSearchRequest
    {
        /// <summary>
        /// Initializes a new instance of the TagsSearchRequest class.
        /// </summary>
        public TagsSearchRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TagsSearchRequest class.
        /// </summary>
        public TagsSearchRequest(string searchPattern = default(string), int? count = default(int?))
        {
            SearchPattern = searchPattern;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchPattern")]
        public string SearchPattern { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
