// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UnbindTagRequest
    {
        /// <summary>
        /// Initializes a new instance of the UnbindTagRequest class.
        /// </summary>
        public UnbindTagRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UnbindTagRequest class.
        /// </summary>
        public UnbindTagRequest(UnbindTagRequestFileTag fileTag)
        {
            FileTag = fileTag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileTag")]
        public UnbindTagRequestFileTag FileTag { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FileTag == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FileTag");
            }
            if (FileTag != null)
            {
                FileTag.Validate();
            }
        }
    }
}
