// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Lilin.WebApi.Client.Models
{
    using System.Linq;

    public partial class UnbindTagRequestFileTag : FileTagRequest
    {
        /// <summary>
        /// Initializes a new instance of the UnbindTagRequestFileTag class.
        /// </summary>
        public UnbindTagRequestFileTag()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UnbindTagRequestFileTag class.
        /// </summary>
        /// <param name="source">Possible values include: 'Yandere',
        /// 'Danbooru', 'Sankaku', 'Manual'</param>
        public UnbindTagRequestFileTag(System.Guid tagId, System.Guid fileId, MetadataSource source, string value = default(string))
            : base(tagId, fileId, source, value)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
