// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Room.HttpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CollectionFileResponse
    {
        /// <summary>
        /// Initializes a new instance of the CollectionFileResponse class.
        /// </summary>
        public CollectionFileResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CollectionFileResponse class.
        /// </summary>
        public CollectionFileResponse(System.Guid? id = default(System.Guid?), System.Guid? collectionId = default(System.Guid?), string path = default(string), string md5 = default(string), long? size = default(long?), string originalPath = default(string))
        {
            Id = id;
            CollectionId = collectionId;
            Path = path;
            Md5 = md5;
            Size = size;
            OriginalPath = originalPath;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collectionId")]
        public System.Guid? CollectionId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "md5")]
        public string Md5 { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public long? Size { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "originalPath")]
        public string OriginalPath { get; private set; }

    }
}
