// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Room.HttpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DestinationFolderResponse
    {
        /// <summary>
        /// Initializes a new instance of the DestinationFolderResponse class.
        /// </summary>
        public DestinationFolderResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DestinationFolderResponse class.
        /// </summary>
        public DestinationFolderResponse(System.Guid? id = default(System.Guid?), System.Guid? collectionId = default(System.Guid?), string path = default(string), bool? shouldCreateSubfoldersByHash = default(bool?), bool? shouldRenameByHash = default(bool?), string formatErrorSubfolder = default(string), string hashErrorSubfolder = default(string), string withoutHashErrorSubfolder = default(string))
        {
            Id = id;
            CollectionId = collectionId;
            Path = path;
            ShouldCreateSubfoldersByHash = shouldCreateSubfoldersByHash;
            ShouldRenameByHash = shouldRenameByHash;
            FormatErrorSubfolder = formatErrorSubfolder;
            HashErrorSubfolder = hashErrorSubfolder;
            WithoutHashErrorSubfolder = withoutHashErrorSubfolder;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collectionId")]
        public System.Guid? CollectionId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shouldCreateSubfoldersByHash")]
        public bool? ShouldCreateSubfoldersByHash { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shouldRenameByHash")]
        public bool? ShouldRenameByHash { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formatErrorSubfolder")]
        public string FormatErrorSubfolder { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hashErrorSubfolder")]
        public string HashErrorSubfolder { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "withoutHashErrorSubfolder")]
        public string WithoutHashErrorSubfolder { get; private set; }

    }
}
