// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Room.HttpClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SourceFolders.
    /// </summary>
    public static partial class SourceFoldersExtensions
    {
            /// <summary>
            /// Get all source folders for collection.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='collectionId'>
            /// The collection id.
            /// </param>
            public static IList<SourceFolderResponse> GetAll(this ISourceFolders operations, System.Guid collectionId)
            {
                return operations.GetAllAsync(collectionId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get all source folders for collection.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='collectionId'>
            /// The collection id.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<SourceFolderResponse>> GetAllAsync(this ISourceFolders operations, System.Guid collectionId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllWithHttpMessagesAsync(collectionId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a source folder for collection.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='collectionId'>
            /// The collection id.
            /// </param>
            /// <param name='body'>
            /// Source folder parameters.
            /// </param>
            public static SourceFolderResponse Create(this ISourceFolders operations, System.Guid collectionId, SourceFolderCreateRequest body = default(SourceFolderCreateRequest))
            {
                return operations.CreateAsync(collectionId, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a source folder for collection.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='collectionId'>
            /// The collection id.
            /// </param>
            /// <param name='body'>
            /// Source folder parameters.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SourceFolderResponse> CreateAsync(this ISourceFolders operations, System.Guid collectionId, SourceFolderCreateRequest body = default(SourceFolderCreateRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(collectionId, body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete the source folder.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// Id of the folder that will be deleted.
            /// </param>
            /// <param name='collectionId'>
            /// </param>
            public static void Delete(this ISourceFolders operations, System.Guid guid, string collectionId)
            {
                operations.DeleteAsync(guid, collectionId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete the source folder.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// Id of the folder that will be deleted.
            /// </param>
            /// <param name='collectionId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteAsync(this ISourceFolders operations, System.Guid guid, string collectionId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteWithHttpMessagesAsync(guid, collectionId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
