// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Room.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CollectionFilesRequest
    {
        /// <summary>
        /// Initializes a new instance of the CollectionFilesRequest class.
        /// </summary>
        public CollectionFilesRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CollectionFilesRequest class.
        /// </summary>
        public CollectionFilesRequest(System.Guid? collectionId = default(System.Guid?), IList<System.Guid?> collectionFileIds = default(IList<System.Guid?>), string path = default(string), IList<string> md5 = default(IList<string>), int? count = default(int?), int? skip = default(int?))
        {
            CollectionId = collectionId;
            CollectionFileIds = collectionFileIds;
            Path = path;
            Md5 = md5;
            Count = count;
            Skip = skip;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collectionId")]
        public System.Guid? CollectionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collectionFileIds")]
        public IList<System.Guid?> CollectionFileIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "md5")]
        public IList<string> Md5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skip")]
        public int? Skip { get; set; }

    }
}
