// <auto-generated />
using System;
using ImoutoRebirth.Room.Database;
using ImoutoRebirth.Room.Domain.IntegrityAggregate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImoutoRebirth.Room.Database.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    partial class RoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "integrity_status", new[] { "hash_mismatch", "missing", "ok" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "report_status", new[] { "building", "cancelled", "completed", "created", "paused" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.CollectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.CollectionFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalPath")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("Md5");

                    b.HasIndex("Path");

                    b.HasIndex("CollectionId", "Md5", "IsRemoved")
                        .IsUnique()
                        .HasFilter("NOT \"IsRemoved\"");

                    b.ToTable("CollectionFiles");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.DestinationFolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormatErrorSubfolder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("!FormatError");

                    b.Property<string>("HashErrorSubfolder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("!HashError");

                    b.Property<Instant>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShouldCreateSubfoldersByHash")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldRenameByHash")
                        .HasColumnType("boolean");

                    b.Property<string>("WithoutHashErrorSubfolder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("!WithoutHashError");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.ToTable("DestinationFolders");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportCollectionEntity", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpectedTotalFileCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProcessedFileCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("ReportExportedFiles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ReportId", "CollectionId");

                    b.ToTable("IntegrityReportCollections", (string)null);
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportEntity", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExpectedTotalFileCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExportToFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessedFileCount")
                        .HasColumnType("integer");

                    b.Property<Instant>("StartedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ReportStatus>("Status")
                        .HasColumnType("report_status");

                    b.HasKey("ReportId");

                    b.ToTable("IntegrityReports", (string)null);
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportFileStatusEntity", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActualHash")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedFullPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<string>("ReadingProblem")
                        .HasColumnType("text");

                    b.Property<IntegrityStatus>("Status")
                        .HasColumnType("integrity_status");

                    b.HasKey("ReportId", "CollectionId", "FileId");

                    b.ToTable("IntegrityReportFileStatuses", (string)null);
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.SourceFolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWebhookUploadEnabled")
                        .HasColumnType("boolean");

                    b.Property<Instant>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShouldAddTagFromFilename")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldCheckFormat")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldCheckHashFromName")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldCreateTagsFromSubfolders")
                        .HasColumnType("boolean");

                    b.Property<string>("WebhookUploadUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("_supportedExtensions")
                        .HasColumnType("text")
                        .HasColumnName("SupportedExtensions");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("SourceFolders");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.CollectionFileEntity", b =>
                {
                    b.HasOne("ImoutoRebirth.Room.Database.Entities.CollectionEntity", "Collection")
                        .WithMany("Files")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.DestinationFolderEntity", b =>
                {
                    b.HasOne("ImoutoRebirth.Room.Database.Entities.CollectionEntity", "Collection")
                        .WithOne("DestinationFolder")
                        .HasForeignKey("ImoutoRebirth.Room.Database.Entities.DestinationFolderEntity", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportCollectionEntity", b =>
                {
                    b.HasOne("ImoutoRebirth.Room.Database.Entities.IntegrityReportEntity", "Report")
                        .WithMany("Collections")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportFileStatusEntity", b =>
                {
                    b.HasOne("ImoutoRebirth.Room.Database.Entities.IntegrityReportCollectionEntity", "Collection")
                        .WithMany("FileStatuses")
                        .HasForeignKey("ReportId", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.SourceFolderEntity", b =>
                {
                    b.HasOne("ImoutoRebirth.Room.Database.Entities.CollectionEntity", "Collection")
                        .WithMany("SourceFolders")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.CollectionEntity", b =>
                {
                    b.Navigation("DestinationFolder");

                    b.Navigation("Files");

                    b.Navigation("SourceFolders");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportCollectionEntity", b =>
                {
                    b.Navigation("FileStatuses");
                });

            modelBuilder.Entity("ImoutoRebirth.Room.Database.Entities.IntegrityReportEntity", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
