//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagesDBLibrary.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagsInImages = new HashSet<TagsInImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public bool HasValue { get; set; }
    
        public virtual TagType TagType { get; set; }
        public virtual ICollection<TagsInImage> TagsInImages { get; set; }
    }
}
