//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagesDBLibrary.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsInImage
    {
        public int ImageFK { get; set; }
        public int TagFK { get; set; }
        public bool UserAdded { get; set; }
        public string Value { get; set; }
        public System.DateTime AddedTime { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
