//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagesDBLibrary.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagSet
    {
        public TagSet()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int FKImage { get; set; }
        public string Type { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
