// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ImoutoRebirth.Room.WebApi.Client
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IImoutoRebirthRoomWebApiClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the ICollectionFiles.
        /// </summary>
        ICollectionFiles CollectionFiles { get; }

        /// <summary>
        /// Gets the ICollections.
        /// </summary>
        ICollections Collections { get; }

        /// <summary>
        /// Gets the IDestinationFolder.
        /// </summary>
        IDestinationFolder DestinationFolder { get; }

        /// <summary>
        /// Gets the ISourceFolders.
        /// </summary>
        ISourceFolders SourceFolders { get; }

    }
}
